apiVersion: apps/v1
kind: Deployment
metadata:
  name: zebec-app
  labels:
    app: zebec-app
spec:
  selector:
    matchLabels:
      app: zebec-app
  replicas: {{ .Values.frontend.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zebec-app
    spec:
      containers:
        - name: zebec-app
          image: {{ .Values.frontend.imageUri }}
          ports:
            - containerPort: {{ .Values.frontendService.containerPort }}
