apiVersion: v1
kind: Service
metadata:
  name: zebec-app-service
spec:
  selector:
    app: zebec-app
  ports:
    - name: http
      port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.containerPort }}
      protocol: TCP
  type: NodePort