import React, { FC } from "react";
import Head from "next/head";
import Navbar from "./Navbar";

interface LayoutProps {
  pageTitle: string;
  children: React.ReactNode;
}

const Layout: FC<LayoutProps> = ({ pageTitle, children }) => {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>{children}</main>
    </>
  );
};

export default Layout;
